myid=global.npcId;global.npcId+=1;if (global.npcId>65535){  global.npcId=0;}type=argument0;npc_sprite_init(type);dir=0;knockDir=0;prevdir=dir;grav=0;vspd=0;right=true;synch_time=65;target=0;switch (type){  
case 0:   {    name="Blob";    maxhp=64;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=2.3;    flee=false;    damage=11;    damageDelay=1.5;    attackLife=5;    attackHorizSize=16;    attackVertSize=16;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.3;    hits=1;    sight=260;    thinkTime=40;    thinkMod=15;    attackRate=30;    attackMod=20;    jump=10;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=0;  } break;  
case 1:   {    name="Rock Demon";    maxhp=260;    hp=maxhp;    defense=4;    knockResist=30;    maxSpeed=2;    flee=false;    damage=33;    damageDelay=2.4;    attackLife=9;    attackHorizSize=65;    attackVertSize=36;    attackHorizOffset=-10;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.3;    hits=2;    sight=350;    thinkTime=60;    thinkMod=20;    attackRate=60;    attackMod=20;    jump=8;    jumpRate=20;    jumpMod=5;    horizKnock=7;    vertKnock=-7;    spawnOffset=0;  } break;  
case 2:   {    name="Big Blob Boss";    maxhp=800;    hp=maxhp;    defense=6;    knockResist=45;    maxSpeed=2.8;    flee=false;    damage=30;    damageDelay=1.5;    attackLife=5;    attackHorizSize=48;    attackVertSize=48;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.3;    hits=3;    sight=350;    thinkTime=40;    thinkMod=15;    attackRate=30;    attackMod=20;    jump=14;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=44  } break;  
case 3:   {    name="Bandit";    maxhp=160;    hp=maxhp;    defense=2;    knockResist=10;    maxSpeed=2.4;    flee=false;    damage=20;    damageDelay=1;    attackLife=5;    attackHorizSize=16;    attackVertSize=16;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.2;    hits=1;    sight=200;    thinkTime=25;    thinkMod=20;    attackRate=18;    attackMod=15;    jump=10;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=30;  } break;  

case 4:   {    name="Gift Box";    maxhp=1;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=0;    flee=false;    damage=0;    damageDelay=0;    attackLife=0;    attackHorizSize=0;    attackVertSize=0;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=0;    attackSpeed=0;    hits=0;    sight=0;    thinkTime=-1;    thinkMod=0;    attackRate=-1;    attackMod=0;    jump=0;    jumpRate=-1;    jumpMod=0;    horizKnock=0;    vertKnock=0;    spawnOffset=700;  } break;  

case 5:   {    name="Bunny";    maxhp=65;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=5.1;    flee=true;    damage=0;    damageDelay=0;    attackLife=0;    attackHorizSize=0;    attackVertSize=0;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=0;    attackSpeed=0;    hits=0;    sight=235;    thinkTime=20;    thinkMod=5;    attackRate=-1;    attackMod=0;    jump=12;    jumpRate=10;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=0;  } break;  
case 6:   {    name="Easter Egg";    maxhp=1;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=0;    flee=false;    damage=0;    damageDelay=0;    attackLife=0;    attackHorizSize=0;    attackVertSize=0;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=0;    attackSpeed=0;    hits=0;    sight=0;    thinkTime=-1;    thinkMod=0;    attackRate=-1;    attackMod=0;    jump=0;    jumpRate=-1;    jumpMod=0;    horizKnock=0;    vertKnock=0;    spawnOffset=12;  } break;  
case 7:   {    name="Bonehead";    maxhp=434;    hp=maxhp;    defense=2;    knockResist=15;    maxSpeed=3.1;    flee=false;    damage=29;    damageDelay=2;    attackLife=6;    attackHorizSize=25;    attackVertSize=50;    attackHorizOffset=5;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.2;    hits=1;    sight=300;    thinkTime=25;    thinkMod=20;    attackRate=10;    attackMod=10;    jump=11;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=61;  } break;  
case 8:   {    name="Sand Fiend";    maxhp=1200;    hp=maxhp;    defense=5;    knockResist=50;    maxSpeed=3.6;    flee=false;    damage=59;    damageDelay=9;    attackLife=6;    attackHorizSize=60;    attackVertSize=100;    attackHorizOffset=10;    attackVertOffset=-10;    attackDaze=30;    attackSpeed=.4;    hits=3;    sight=300;    thinkTime=50;    thinkMod=20;    attackRate=35;    attackMod=25;    jump=10;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=94;  } break;  
case 9:   {    name="Cacti";    maxhp=544;    hp=maxhp;    defense=2;    knockResist=25;    maxSpeed=2.2;    flee=false;    damage=38;    damageDelay=2;    attackLife=5;    attackHorizSize=25;    attackVertSize=16;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.3;    hits=1;    sight=280;    thinkTime=30;    thinkMod=15;    attackRate=20;    attackMod=10;    jump=12;    jumpRate=14;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=70;  } break;  
case 10:   {    name="Dark Sage";    maxhp=6000;    hp=maxhp;    defense=12;    knockResist=30;    maxSpeed=3.0;    flee=false;    damage=62;    damageDelay=6;    attackLife=8;    attackHorizSize=129;    attackVertSize=80;    attackHorizOffset=20;    attackVertOffset=0;    attackDaze=60;    attackSpeed=.3;    hits=8;    sight=500;    thinkTime=60;    thinkMod=25;    attackRate=50;    attackMod=20;    jump=11;    jumpRate=60;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=101;  } break;  
case 11:   {    name="Black Bunny";    maxhp=85;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=6.5;    flee=true;    damage=0;    damageDelay=0;    attackLife=0;    attackHorizSize=0;    attackVertSize=0;    attackHorizOffset=0;    attackVertOffset=0;    attackSpeed=0;    attackDaze=0;    hits=0;    sight=225;    thinkTime=20;    thinkMod=5;    attackRate=-1;    attackMod=0;    jump=12;    jumpRate=10;    jumpMod=6;    horizKnock=0;    vertKnock=0;    spawnOffset=0;  } break;  
case 12:   {    name="Rock Beast";    maxhp=2400;    hp=maxhp;    defense=5;    knockResist=95;    maxSpeed=2.4;    flee=false;    damage=36;    damageDelay=4;    attackLife=10;    attackHorizSize=85;    attackVertSize=60;    attackHorizOffset=65;    attackVertOffset=15;    attackDaze=30;    attackSpeed=.3;    hits=3;    sight=380;    thinkTime=65;    thinkMod=50;    attackRate=40;    attackMod=20;    jump=7;    jumpRate=20;    jumpMod=5;    horizKnock=8;    vertKnock=-6;    spawnOffset=20;  } break;  
case 13:   {    name="Jacko Fiend";    maxhp=145;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=2.5;    flee=false;    damage=18;    damageDelay=2;    attackLife=5;    attackHorizSize=30;    attackVertSize=30;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.24;    hits=1;    sight=300;    thinkTime=35;    thinkMod=15;    attackRate=25;    attackMod=20;    jump=10;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=55;  } break;  
case 14:   {    name="Ghost";    maxhp=300;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=3.0;    flee=false;    damage=20;    damageDelay=2;    attackLife=7;    attackHorizSize=42;    attackVertSize=25;    attackHorizOffset=-5;    attackVertOffset=-5;    attackDaze=30;    attackSpeed=.26;    hits=3;    sight=300;    thinkTime=25;    thinkMod=14;    attackRate=20;    attackMod=10;    jump=11;    jumpRate=30;    jumpMod=5;    horizKnock=4;    vertKnock=-4;    spawnOffset=55;  } break; 

case 15:   {    name="Deluxe Gift Box";    maxhp=1;    hp=maxhp;    defense=0;    knockResist=0;    maxSpeed=0;    flee=false;    damage=0;    damageDelay=0;    attackLife=0;    attackHorizSize=0;    attackVertSize=0;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=0;    attackSpeed=0;    hits=0;    sight=0;    thinkTime=-1;    thinkMod=0;    attackRate=-1;    attackMod=0;    jump=0;    jumpRate=-1;    jumpMod=0;    horizKnock=0;    vertKnock=0;    spawnOffset=700;  } break;

case 16:   {    name="Sand Giant";    maxhp=15000;    hp=maxhp;    defense=12;    knockResist=95;    maxSpeed=3.6;    flee=false;    damage=150;    damageDelay=9;    attackLife=6;    attackHorizSize=350;    attackVertSize=400;    attackHorizOffset=10;    attackVertOffset=-10;    attackDaze=30;    attackSpeed=.4;    hits=6;    sight=600;    thinkTime=50;    thinkMod=20;    attackRate=45;    attackMod=25;    jump=10;    jumpRate=30;    jumpMod=5;    horizKnock=20;    vertKnock=-12;    spawnOffset=282;  } break;  
case 17:   {    name="Bandit Assassin";    maxhp=1700;    hp=maxhp;    defense=2;    knockResist=20;    maxSpeed=3.8;    flee=false;    damage=34;    damageDelay=1;    attackLife=5;    attackHorizSize=20;    attackVertSize=16;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    hits=4;    sight=350;    thinkTime=25;    thinkMod=20;    attackRate=35;    attackMod=15;    jump=10;    jumpRate=30;    jumpMod=5;    attackSpeed=.2;    horizKnock=0;    vertKnock=0;    spawnOffset=30;  } break;      
//Snowman
case 18:   {    
    name="Snowman";    
    maxhp=8000;    
    hp=maxhp;    
    defense=6;    
    knockResist=0;    
    maxSpeed=3;    
    flee=false;    
    damage=60;    
    damageDelay=10;    
    attackLife=3;    
    attackHorizSize=660;    
    attackVertSize=80;    
    attackHorizOffset=-330;    
    attackVertOffset=80;    
    attackDaze=30;    
    hits=30;    
    sight=700;    
    thinkTime=25;    
    thinkMod=20;    
    attackRate=35;    
    attackMod=15;    
    jump=10;    
    jumpRate=30;    
    jumpMod=5;    
    attackSpeed=.25;    
    horizKnock=0;    
    vertKnock=0;    
    spawnOffset=238;  
    } break; 
    case 19:   {    name="Demon";    maxhp=1600;    hp=maxhp;    defense=10;    knockResist=50;    maxSpeed=2.1;    flee=false;    damage=70;    damageDelay=1.5;    attackLife=6;    attackHorizSize=25;    attackVertSize=50;    attackHorizOffset=5;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.2;    hits=1;    sight=300;    thinkTime=25;    thinkMod=20;    attackRate=10;    attackMod=10;    jump=11;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=61;  } break;  
    case 20:   {    name="Dragon";    maxhp=8500;    hp=maxhp;    defense=14;    knockResist=10;    maxSpeed=3.0;    flee=false;    damage=84;    damageDelay=6;    attackLife=8;    attackHorizSize=90;    attackVertSize=80;    attackHorizOffset=20;    attackVertOffset=0;    attackDaze=60;    attackSpeed=.3;    hits=8;    sight=500;    thinkTime=60;    thinkMod=25;    attackRate=50;    attackMod=20;    jump=11;    jumpRate=60;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=101;  } break;  
    case 21:   {    name="Octo";    maxhp=550;    hp=maxhp;    defense=2;    knockResist=15;    maxSpeed=2.2;    flee=false;    damage=31;    damageDelay=2;    attackLife=6;    attackHorizSize=25;    attackVertSize=50;    attackHorizOffset=5;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.2;    hits=1;    sight=300;    thinkTime=25;    thinkMod=20;    attackRate=10;    attackMod=10;    jump=11;    jumpRate=30;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=61;  } break;  
    case 22:   {    name="Frog";    maxhp=125;    hp=maxhp;    defense=2;    knockResist=15;    maxSpeed=3.2;    flee=false;    damage=21;    damageDelay=4;    attackLife=6;    attackHorizSize=75;    attackVertSize=25;    attackHorizOffset=5;    attackVertOffset=0;    attackDaze=30;    attackSpeed=.5;    hits=1;    sight=250;    thinkTime=25;    thinkMod=20;    attackRate=75;    attackMod=10;    jump=18;    jumpRate=45;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=700;  } break; 
    case 23:   {    name="Elite Dark Sage";    maxhp=7500;    hp=maxhp;    defense=12;    knockResist=10;    maxSpeed=3.5;    flee=false;    damage=82;    damageDelay=6;    attackLife=8;    attackHorizSize=129;    attackVertSize=80;    attackHorizOffset=20;    attackVertOffset=0;    attackDaze=60;    attackSpeed=.3;    hits=8;    sight=500;    thinkTime=60;    thinkMod=25;    attackRate=50;    attackMod=20;    jump=11;    jumpRate=60;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=101;  } break;  
    case 24:   {    name="Elite Rock Beast";    maxhp=3900;    hp=maxhp;    defense=5;    knockResist=95;    maxSpeed=2.9;    flee=false;    damage=56;    damageDelay=4;    attackLife=10;    attackHorizSize=85;    attackVertSize=60;    attackHorizOffset=65;    attackVertOffset=15;    attackDaze=30;    attackSpeed=.3;    hits=3;    sight=380;    thinkTime=65;    thinkMod=50;    attackRate=40;    attackMod=20;    jump=7;    jumpRate=20;    jumpMod=5;    horizKnock=8;    vertKnock=-6;    spawnOffset=20;  } break;
    case 25:   {    name="Elite Bandit Assassin";    maxhp=3200;    hp=maxhp;    defense=2;    knockResist=10;    maxSpeed=4.3;    flee=false;    damage=54;    damageDelay=1;    attackLife=5;    attackHorizSize=20;    attackVertSize=16;    attackHorizOffset=0;    attackVertOffset=0;    attackDaze=30;    hits=4;    sight=350;    thinkTime=25;    thinkMod=20;    attackRate=35;    attackMod=15;    jump=10;    jumpRate=30;    jumpMod=5;    attackSpeed=.2;    horizKnock=0;    vertKnock=0;    spawnOffset=30;  } break;  
    case 26:   {    name="Elite Dragon";    maxhp=10000;    hp=maxhp;    defense=14;    knockResist=10;    maxSpeed=3.5;    flee=false;    damage=104;    damageDelay=6;    attackLife=8;    attackHorizSize=90;    attackVertSize=80;    attackHorizOffset=20;    attackVertOffset=0;    attackDaze=60;    attackSpeed=.3;    hits=8;    sight=500;    thinkTime=60;    thinkMod=25;    attackRate=50;    attackMod=20;    jump=11;    jumpRate=60;    jumpMod=5;    horizKnock=0;    vertKnock=0;    spawnOffset=101;  } break;    
}
y-=spawnOffset;sprite_speed=standardSprSpeed;sprite_index=stand_right;alarm[2]=thinkTime+random(thinkMod);alarm[4]=attackRate+random(attackMod);alarm[6]=jumpRate+random(jumpMod);
